/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ConfidentialPaymentGateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_CLIFF_OFFSET"
      | "DEFAULT_VEST_DURATION"
      | "MODE_LIQUID"
      | "MODE_VESTING"
      | "MODE_YIELD"
      | "admin"
      | "authorizedProtocols"
      | "cUSDT"
      | "cancelIntent"
      | "confidentialProtocolId"
      | "createPaymentIntent"
      | "deposit"
      | "executeIntent"
      | "flowRegistry"
      | "getBalance"
      | "getRegisteredProtocols"
      | "hasBalance"
      | "intents"
      | "protocolNames"
      | "registerProtocol"
      | "revokeProtocol"
      | "routeFromProtocol"
      | "routePayment"
      | "sanctioned"
      | "setModules"
      | "setSanctioned"
      | "transferAdmin"
      | "vestingModule"
      | "yieldVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferred"
      | "Deposited"
      | "PaymentIntentCancelled"
      | "PaymentIntentCreated"
      | "PaymentIntentSettled"
      | "PaymentRouted"
      | "ProtocolRegistered"
      | "ProtocolRevoked"
      | "SanctionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_CLIFF_OFFSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_VEST_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MODE_LIQUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MODE_VESTING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MODE_YIELD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizedProtocols",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "cUSDT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPaymentIntent",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flowRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredProtocols",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "intents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "protocolNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProtocol",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeProtocol",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routeFromProtocol",
    values: [AddressLike, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "routePayment",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sanctioned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setModules",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSanctioned",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "yieldVault",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_CLIFF_OFFSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_VEST_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MODE_LIQUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MODE_VESTING",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MODE_YIELD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cUSDT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPaymentIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flowRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeFromProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sanctioned", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setModules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSanctioned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yieldVault", data: BytesLike): Result;
}

export namespace AdminTransferredEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentIntentCancelledEvent {
  export type InputTuple = [intentId: BytesLike];
  export type OutputTuple = [intentId: string];
  export interface OutputObject {
    intentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentIntentCreatedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    from: AddressLike,
    to: AddressLike,
    routingMode: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    from: string,
    to: string,
    routingMode: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    intentId: string;
    from: string;
    to: string;
    routingMode: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentIntentSettledEvent {
  export type InputTuple = [intentId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [intentId: string, timestamp: bigint];
  export interface OutputObject {
    intentId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRoutedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    mode: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    mode: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    mode: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolRegisteredEvent {
  export type InputTuple = [protocol: AddressLike, name: string];
  export type OutputTuple = [protocol: string, name: string];
  export interface OutputObject {
    protocol: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolRevokedEvent {
  export type InputTuple = [protocol: AddressLike];
  export type OutputTuple = [protocol: string];
  export interface OutputObject {
    protocol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SanctionUpdatedEvent {
  export type InputTuple = [user: AddressLike, status: boolean];
  export type OutputTuple = [user: string, status: boolean];
  export interface OutputObject {
    user: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPaymentGate extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPaymentGate;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPaymentGateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_CLIFF_OFFSET: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_VEST_DURATION: TypedContractMethod<[], [bigint], "view">;

  MODE_LIQUID: TypedContractMethod<[], [bigint], "view">;

  MODE_VESTING: TypedContractMethod<[], [bigint], "view">;

  MODE_YIELD: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  authorizedProtocols: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  cUSDT: TypedContractMethod<[], [string], "view">;

  cancelIntent: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPaymentIntent: TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      routingMode: BigNumberish,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  executeIntent: TypedContractMethod<
    [intentId: BytesLike],
    [void],
    "nonpayable"
  >;

  flowRegistry: TypedContractMethod<[], [string], "view">;

  getBalance: TypedContractMethod<[user: AddressLike], [string], "view">;

  getRegisteredProtocols: TypedContractMethod<
    [],
    [[string[], string[]] & { protocols: string[]; names: string[] }],
    "view"
  >;

  hasBalance: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  intents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        from: string;
        to: string;
        encryptedAmount: string;
        routingMode: bigint;
        expiresAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  protocolNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerProtocol: TypedContractMethod<
    [protocol: AddressLike, name: string],
    [void],
    "nonpayable"
  >;

  revokeProtocol: TypedContractMethod<
    [protocol: AddressLike],
    [void],
    "nonpayable"
  >;

  routeFromProtocol: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      routingMode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  routePayment: TypedContractMethod<
    [
      recipient: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      mode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  sanctioned: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setModules: TypedContractMethod<
    [_yieldVault: AddressLike, _vestingModule: AddressLike],
    [void],
    "nonpayable"
  >;

  setSanctioned: TypedContractMethod<
    [user: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  vestingModule: TypedContractMethod<[], [string], "view">;

  yieldVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_CLIFF_OFFSET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_VEST_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MODE_LIQUID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MODE_VESTING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MODE_YIELD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedProtocols"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cUSDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelIntent"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPaymentIntent"
  ): TypedContractMethod<
    [
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      routingMode: BigNumberish,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeIntent"
  ): TypedContractMethod<[intentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "flowRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRegisteredProtocols"
  ): TypedContractMethod<
    [],
    [[string[], string[]] & { protocols: string[]; names: string[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasBalance"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, boolean] & {
        from: string;
        to: string;
        encryptedAmount: string;
        routingMode: bigint;
        expiresAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerProtocol"
  ): TypedContractMethod<
    [protocol: AddressLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeProtocol"
  ): TypedContractMethod<[protocol: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routeFromProtocol"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      routingMode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routePayment"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike,
      mode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sanctioned"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setModules"
  ): TypedContractMethod<
    [_yieldVault: AddressLike, _vestingModule: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSanctioned"
  ): TypedContractMethod<
    [user: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yieldVault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AdminTransferred"
  ): TypedContractEvent<
    AdminTransferredEvent.InputTuple,
    AdminTransferredEvent.OutputTuple,
    AdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentIntentCancelled"
  ): TypedContractEvent<
    PaymentIntentCancelledEvent.InputTuple,
    PaymentIntentCancelledEvent.OutputTuple,
    PaymentIntentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentIntentCreated"
  ): TypedContractEvent<
    PaymentIntentCreatedEvent.InputTuple,
    PaymentIntentCreatedEvent.OutputTuple,
    PaymentIntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentIntentSettled"
  ): TypedContractEvent<
    PaymentIntentSettledEvent.InputTuple,
    PaymentIntentSettledEvent.OutputTuple,
    PaymentIntentSettledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRouted"
  ): TypedContractEvent<
    PaymentRoutedEvent.InputTuple,
    PaymentRoutedEvent.OutputTuple,
    PaymentRoutedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolRegistered"
  ): TypedContractEvent<
    ProtocolRegisteredEvent.InputTuple,
    ProtocolRegisteredEvent.OutputTuple,
    ProtocolRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolRevoked"
  ): TypedContractEvent<
    ProtocolRevokedEvent.InputTuple,
    ProtocolRevokedEvent.OutputTuple,
    ProtocolRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SanctionUpdated"
  ): TypedContractEvent<
    SanctionUpdatedEvent.InputTuple,
    SanctionUpdatedEvent.OutputTuple,
    SanctionUpdatedEvent.OutputObject
  >;

  filters: {
    "AdminTransferred(address,address)": TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;
    AdminTransferred: TypedContractEvent<
      AdminTransferredEvent.InputTuple,
      AdminTransferredEvent.OutputTuple,
      AdminTransferredEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "PaymentIntentCancelled(bytes32)": TypedContractEvent<
      PaymentIntentCancelledEvent.InputTuple,
      PaymentIntentCancelledEvent.OutputTuple,
      PaymentIntentCancelledEvent.OutputObject
    >;
    PaymentIntentCancelled: TypedContractEvent<
      PaymentIntentCancelledEvent.InputTuple,
      PaymentIntentCancelledEvent.OutputTuple,
      PaymentIntentCancelledEvent.OutputObject
    >;

    "PaymentIntentCreated(bytes32,address,address,uint8,uint256)": TypedContractEvent<
      PaymentIntentCreatedEvent.InputTuple,
      PaymentIntentCreatedEvent.OutputTuple,
      PaymentIntentCreatedEvent.OutputObject
    >;
    PaymentIntentCreated: TypedContractEvent<
      PaymentIntentCreatedEvent.InputTuple,
      PaymentIntentCreatedEvent.OutputTuple,
      PaymentIntentCreatedEvent.OutputObject
    >;

    "PaymentIntentSettled(bytes32,uint256)": TypedContractEvent<
      PaymentIntentSettledEvent.InputTuple,
      PaymentIntentSettledEvent.OutputTuple,
      PaymentIntentSettledEvent.OutputObject
    >;
    PaymentIntentSettled: TypedContractEvent<
      PaymentIntentSettledEvent.InputTuple,
      PaymentIntentSettledEvent.OutputTuple,
      PaymentIntentSettledEvent.OutputObject
    >;

    "PaymentRouted(address,address,uint8,uint256)": TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;
    PaymentRouted: TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;

    "ProtocolRegistered(address,string)": TypedContractEvent<
      ProtocolRegisteredEvent.InputTuple,
      ProtocolRegisteredEvent.OutputTuple,
      ProtocolRegisteredEvent.OutputObject
    >;
    ProtocolRegistered: TypedContractEvent<
      ProtocolRegisteredEvent.InputTuple,
      ProtocolRegisteredEvent.OutputTuple,
      ProtocolRegisteredEvent.OutputObject
    >;

    "ProtocolRevoked(address)": TypedContractEvent<
      ProtocolRevokedEvent.InputTuple,
      ProtocolRevokedEvent.OutputTuple,
      ProtocolRevokedEvent.OutputObject
    >;
    ProtocolRevoked: TypedContractEvent<
      ProtocolRevokedEvent.InputTuple,
      ProtocolRevokedEvent.OutputTuple,
      ProtocolRevokedEvent.OutputObject
    >;

    "SanctionUpdated(address,bool)": TypedContractEvent<
      SanctionUpdatedEvent.InputTuple,
      SanctionUpdatedEvent.OutputTuple,
      SanctionUpdatedEvent.OutputObject
    >;
    SanctionUpdated: TypedContractEvent<
      SanctionUpdatedEvent.InputTuple,
      SanctionUpdatedEvent.OutputTuple,
      SanctionUpdatedEvent.OutputObject
    >;
  };
}
